### PR TITLE
bumped arkime version in Dockerfile and helm chart from 4.2.0 to 4.3.…

### LINKED ISSUE #30: update arkime from 4.2.0 to 4.3.2
Arkime version is a bit outdated, this tracks the work to upgrade it and test both here and integrated in dco-core.

This was picked as a good "first issue" for Tim to use while dogfooding recent collaboration on the collaboration guides with @Vandiver247.

### PR DESCRIPTION
**Pull request by timblaktu**
Closes #30

### CODE REVIEW

**Comment by timblaktu** [comment]
@Vandiver247 although there _are_ tests in this repo, the PR workflow does not build or invoke them - it only builds the image. I assume this is why @docandrew said there were no tests, bc they aren't being run.

So far so good on this PR, and the contrib-dogfooding exercise..

**Comment by timblaktu** [comment]
Go test failed in dco-core package-component stage, in Zarf Package Test [here](https://github.com/naps-dev/dco-core/actions/runs/5416975477/jobs/9847387325#step:20:30), because of an invalid hostname check during cluster testing, presumably because I blindly followed the contrib-guide step #9 which says to use the branch name for the docker image tag variable. This var appears to _become_ part of the cluster or hostname during zarf package testing, and it's probably too long. 

I will change this (and update the contrib-guide) to use the arkime version instead of branch name.

**Comment by timblaktu** [comment]
# Re: trailing `-` in hostname
This is a problem in mine and @laurenmengert's use cases. I modified the top level dco-core go test to properly trim any trailing `-`, as well as to assert (early!) that the clusterName is a valid hostname after sanitization.

# Re: unexpected `**` masking in actions console output 

Digging deeper into this, I see that this masking occurs not only [when explicitly requested using `add-mask` in strings](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#masking-a-value-in-a-log), but also [anytime a secret is referred to](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow).

Grepping dco-core I see that [we are directly referring to secrets in package.yaml workflow](https://github.com/naps-dev/dco-core/blob/183946c548969efca9e386a6a0d04c4d8b23553e/.github/workflows/package.yaml#L28):

```yaml
.github/workflows/package.yaml
28:  S3_PATH: "s3://${{ secrets.AWS_BUCKET }}/naps-dev/${{ inputs.COMPONENT}}/${{ inputs.REF_NAME}}"
54:            -u "${{secrets.XSOAR_USERNAME}}" \
55:            -p "${{secrets.XSOAR_PASSWORD}}" \
61:          echo "${{ secrets.XSOAR_LICENSE }}" >> /tmp/demisto.lic
66:          echo "${{ secrets.POLARITY_LICENSE }}" >> /tmp/polarity.lic
71:          role-to-assume: ${{secrets.AWS_ECR_ROLE}}
92:            -u "${{secrets.REGISTRY1_USERNAME}}" \
93:            -p "${{secrets.REGISTRY1_PASSWORD}}" \
145:          role-to-assume: ${{secrets.AWS_ROLE}}
209:#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
```

..and that these are inherited by each component workflow, e.g. in the arkime workflow](https://github.com/naps-dev/dco-core/blob/183946c548969efca9e386a6a0d04c4d8b23553e/.github/workflows/arkime.yaml#L18):

```yaml
jobs:
  package-create:
    uses: ./.github/workflows/package.yaml
    secrets: inherit
    with:
    # The REF_NAME is referencing the tag or branch name in the arkime repo (not the dco-core repo)
    # if you're making a change to the capability chart change the REF_NAME to the tag or branch name in the capability repo
      REF_NAME: "30-update-to-latest-arkime-version"
      REF_TYPE: "branch"
      ZARF_PACKAGE_NAME: zarf-package-arkime-amd64.tar.zst
      IMAGE_TAG: "30-update-to-latest-arkime-version"
      COMPONENT: "arkime"
```

So, ATM I'm assuming that one of these secrets contains `30` in it, bc as you can see [in the log for the original failure](https://github.com/naps-dev/dco-core/actions/runs/5416975477/jobs/9847387325#step:20:8), the issue for me is that `REF_NAME` is being masked:

```
REF_NAME: ***-update-to-latest-arkime-version
```

and this bleeds into the clusterName, causing the failure downstream when k3d tries to create a cluster.

## But...

Note that it's possible that the masking is a red-herring for my error, and that it will go away after eliminating the trailing hyphen. This would be because the masking chars `**` are NOT actually in the variable.

FYI @laurenmengert @benmountjoy111 @docandrew

**Comment by timblaktu** [comment]
OK, [the workflow resulting from the changes I pushed](https://github.com/naps-dev/dco-core/actions/runs/5425892882/jobs/9867234852) has finally gotten scheduled, and gotten past the clusterName/hostname error. The new code I added shows what's happening (hopefully) very clearly now:

```
TestZarfPackage 2023-06-***T18:55:***Z dco_core_package_test.go:32: clusterName before sanitization: arkime-test-***-update-to-latest-arkime-version
TestZarfPackage 2023-06-***T18:55:***Z dco_core_package_test.go:38: Truncated clusterName to 32 chars for k3d: arkime-test-***-update-to-latest-
TestZarfPackage 2023-06-***T18:55:***Z dco_core_package_test.go:41: clusterName after sanitization: arkime-test-***-update-to-latest
```

So, this confirms that the masking is indeed a red herring, @benmountjoy111.

..and to remind the whole team about how GHA masking works. What I learned here was that `**` masking happens in the workflow console/log when:

1. workflow commands explicitly use `add-mask` in a string.
2. any strings, even substrings, contain secrets, as defined and/or used in the entire workflow being run.

**Review by docandrew — APPROVED** [review]
Thank you!

**Review by jamesallen-atx — APPROVED** [review]

**Pull request merged**
